name: test action
on:
  push:
    branches:
      - v1
  workflow_dispatch:

jobs:
  install:
    strategy:
      matrix:
        env:
          - runner: ubuntu-latest
            os: linux
            arch: amd64
          - runner: macos-latest
            os: darwin
            arch: arm64
    name: test action
    runs-on: ${{ matrix.env.runner }}
    steps:
      - uses: actions/checkout@v4
      - uses: fujiwara/lambroll@v1
        with:
          version: v1.0.3
      - run: |
          lambroll version 2>&1 | fgrep v1.0.3
      - uses: fujiwara/lambroll@v1
        with:
          version: v1.0.4
          os: ${{ matrix.env.os }}
          arch: ${{ matrix.env.arch }}
      - run: |
          lambroll version 2>&1 | fgrep v1.0.4
